/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, UserProfile as PrismaUserProfile } from "@prisma/client";
import { LocalStorageService } from "src/storage/providers/local/local.storage.service";
import { InputJsonValue } from "src/types";
import { FileDownload, FileUpload } from "src/storage/base/storage.types";
import { LocalStorageFile } from "src/storage/providers/local/local.storage.types";

export class UserProfileServiceBase {
  constructor(
    protected readonly prisma: PrismaService,
    protected readonly localStorageService: LocalStorageService
  ) {}

  async count(
    args: Omit<Prisma.UserProfileCountArgs, "select">
  ): Promise<number> {
    return this.prisma.userProfile.count(args);
  }

  async userProfiles(
    args: Prisma.UserProfileFindManyArgs
  ): Promise<PrismaUserProfile[]> {
    return this.prisma.userProfile.findMany(args);
  }
  async userProfile(
    args: Prisma.UserProfileFindUniqueArgs
  ): Promise<PrismaUserProfile | null> {
    return this.prisma.userProfile.findUnique(args);
  }
  async createUserProfile(
    args: Prisma.UserProfileCreateArgs
  ): Promise<PrismaUserProfile> {
    return this.prisma.userProfile.create(args);
  }
  async updateUserProfile(
    args: Prisma.UserProfileUpdateArgs
  ): Promise<PrismaUserProfile> {
    return this.prisma.userProfile.update(args);
  }
  async deleteUserProfile(
    args: Prisma.UserProfileDeleteArgs
  ): Promise<PrismaUserProfile> {
    return this.prisma.userProfile.delete(args);
  }

  async uploadProfilePicture<T extends Prisma.UserProfileFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.UserProfileFindUniqueArgs>,
    file: FileUpload
  ): Promise<PrismaUserProfile> {
    file.filename = `profilePicture-${args.where.id}.${file.filename
      .split(".")
      .pop()}`;
    const containerPath = "profilePicture";
    const profilePicture = await this.localStorageService.uploadFile(
      file,
      [],
      1000000,
      containerPath
    );

    return await this.prisma.userProfile.update({
      where: args.where,

      data: {
        profilePicture: profilePicture as InputJsonValue,
      },
    });
  }

  async downloadProfilePicture<T extends Prisma.UserProfileFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.UserProfileFindUniqueArgs>
  ): Promise<FileDownload> {
    const { profilePicture } = await this.prisma.userProfile.findUniqueOrThrow({
      where: args.where,
    });

    return await this.localStorageService.downloadFile(
      profilePicture as unknown as LocalStorageFile
    );
  }

  async deleteProfilePicture<T extends Prisma.UserProfileFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.UserProfileFindUniqueArgs>
  ): Promise<PrismaUserProfile> {
    const { profilePicture } = await this.prisma.userProfile.findUniqueOrThrow({
      where: args.where,
    });

    await this.localStorageService.deleteFile(
      profilePicture as unknown as LocalStorageFile
    );

    return await this.prisma.userProfile.update({
      where: args.where,

      data: {
        profilePicture: Prisma.DbNull,
      },
    });
  }
}
